import { signInWithPopup } from "firebase/auth";
import { auth,googleProvider } from "../firebase";
import { useNavigate } from "react-router-dom";

function Login(){
    const navigate=useNavigate();
    const googleLogin=async()=>{try{await signInWithPopup(auth,googleProvider);navigate("/")}catch(err){console.error(err);alert("Login Failed")}};
    return <div className="tb-page flex min-h-screen items-center justify-center px-4 py-10"><div className="grid w-full max-w-5xl overflow-hidden rounded-[32px] border border-[#332d28] bg-[#11100f] shadow-[0_30px_100px_rgba(0,0,0,.7)] lg:grid-cols-2"><div className="hidden min-h-[620px] flex-col justify-between bg-gradient-to-br from-[#28160e] via-[#15110e] to-[#0b0b0b] p-12 lg:flex"><div className="text-xl font-black">🍔 Tasty<span className="text-[#ff6b2b]">Bite</span></div><div><div className="tb-label">Welcome back</div><h1 className="mt-4 font-['Playfair_Display'] text-5xl font-black leading-tight text-[#fff8ef]">Good food<br/>starts here.</h1><p className="mt-5 max-w-md leading-7 text-[#a99e94]">Compare meals, discover better deals and let Bite help you decide.</p></div><p className="text-xs font-semibold text-[#6e655e]">Eat better. Spend smarter.</p></div><div className="p-7 sm:p-12"><div className="text-xl font-black lg:hidden">🍔 Tasty<span className="text-[#ff6b2b]">Bite</span></div><div className="mt-10 lg:mt-20"><div className="tb-label">Account</div><h2 className="mt-3 text-3xl font-black text-[#fff8ef]">Welcome back</h2><p className="mt-2 text-sm font-medium text-[#938980]">Sign in with Google to continue.</p><button type="button" onClick={googleLogin} className="tb-orange-button mt-8 w-full">Continue with Google <span>→</span></button><div className="mt-8 rounded-2xl border border-[#302b27] bg-[#171513] p-5 text-sm font-semibold leading-7 text-[#b8ada3]">✓ Compare platform prices<br/>✓ Get Bite AI recommendations<br/>✓ Access protected features</div><button type="button" onClick={()=>navigate("/")} className="mt-5 w-full text-sm font-bold text-[#8f857c] hover:text-[#ff7135]">← Back to home</button></div></div></div></div>;
}
export default Login;